export interface BonusQuestion {
  key: string;
  label: string;
  description: string;
  icon: string;
  type: "player" | "number" | "auto";
  /** Partial credit thresholds for number questions: [exactPts, [withinN, pts], ...] */
  numberScoring?: [number, ...Array<[number, number]>];
  lockDate: string; // "Jun 11" — locks at tournament start
}

export const BONUS_QUESTIONS: BonusQuestion[] = [
  {
    key: "golden_ball",
    label: "Golden Ball",
    description: "Best player of the tournament",
    icon: "⚽",
    type: "player",
    lockDate: "Jun 11",
  },
  {
    key: "golden_boot",
    label: "Golden Boot",
    description: "Top scorer of the tournament",
    icon: "👟",
    type: "player",
    lockDate: "Jun 11",
  },
  {
    key: "golden_glove",
    label: "Golden Glove",
    description: "Best goalkeeper of the tournament",
    icon: "🧤",
    type: "player",
    lockDate: "Jun 11",
  },
  {
    key: "best_young_player",
    label: "Best Young Player",
    description: "Top performer born after Jan 1, 2003",
    icon: "🌟",
    type: "player",
    lockDate: "Jun 11",
  },
  {
    key: "total_goals",
    label: "Total Goals",
    description: "Total goals scored in the tournament (104 matches)",
    icon: "🎯",
    type: "number",
    numberScoring: [5, [3, 3], [7, 1]],
    lockDate: "Jun 11",
  },
  {
    key: "worst_group_team",
    label: "Worst Group Stage Team",
    description: "Auto-calculated from your match picks — the team your predictions say will be worst in the group stage",
    icon: "📉",
    type: "auto",
    lockDate: "Jun 11",
  },
  {
    key: "red_cards",
    label: "Red Cards",
    description: "Total red cards shown in the tournament",
    icon: "🟥",
    type: "number",
    numberScoring: [5, [2, 3], [5, 1]],
    lockDate: "Jun 11",
  },
];

export const BONUS_POINTS = 5;

// ── Player candidate lists (50 + "Other" per award) ─────────────────────────

export const GOLDEN_BALL_PLAYERS: string[] = [
  "Alexis Mac Allister (Argentina)",
  "Antoine Griezmann (France)",
  "Bernardo Silva (Portugal)",
  "Bruno Fernandes (Portugal)",
  "Bukayo Saka (England)",
  "Carlos Vela (Mexico)",
  "Cody Gakpo (Netherlands)",
  "Cole Palmer (England)",
  "Darwin Núñez (Uruguay)",
  "Enzo Fernández (Argentina)",
  "Endrick (Brazil)",
  "Erling Haaland (Norway)",
  "Federico Valverde (Uruguay)",
  "Florian Wirtz (Germany)",
  "Gavi (Spain)",
  "Granit Xhaka (Switzerland)",
  "Hirving Lozano (Mexico)",
  "James Rodríguez (Colombia)",
  "Jamal Musiala (Germany)",
  "João Félix (Portugal)",
  "Jude Bellingham (England)",
  "Julián Álvarez (Argentina)",
  "Kai Havertz (Germany)",
  "Kobbie Mainoo (England)",
  "Kylian Mbappé (France)",
  "Lamine Yamal (Spain)",
  "Lautaro Martínez (Argentina)",
  "Lionel Messi (Argentina)",
  "Luis Díaz (Colombia)",
  "Marcus Rashford (England)",
  "Mohamed Salah (Egypt)",
  "Niclas Füllkrug (Germany)",
  "Ousmane Dembélé (France)",
  "Paulo Dybala (Argentina)",
  "Pedri (Spain)",
  "Phil Foden (England)",
  "Rafael Leão (Portugal)",
  "Richarlison (Brazil)",
  "Rodri (Spain)",
  "Rodrygo (Brazil)",
  "Romelu Lukaku (Belgium)",
  "Sadio Mané (Senegal)",
  "Santiago Giménez (Mexico)",
  "Son Heung-min (South Korea)",
  "Theo Hernández (France)",
  "Vinicius Jr (Brazil)",
  "Vitinha (Portugal)",
  "Warren Zaïre-Emery (France)",
  "Xavi Simons (Netherlands)",
  "Other",
];

export const GOLDEN_BOOT_PLAYERS: string[] = [
  "Alexandre Lacazette (Algeria)",
  "Antoine Griezmann (France)",
  "Bukayo Saka (England)",
  "Carlos Vela (Mexico)",
  "Cody Gakpo (Netherlands)",
  "Cole Palmer (England)",
  "Darwin Núñez (Uruguay)",
  "Donyell Malen (Netherlands)",
  "Endrick (Brazil)",
  "Erling Haaland (Norway)",
  "Federico Valverde (Uruguay)",
  "Florian Wirtz (Germany)",
  "Gonçalo Ramos (Portugal)",
  "Harry Kane (England)",
  "Hirving Lozano (Mexico)",
  "Jamal Musiala (Germany)",
  "João Félix (Portugal)",
  "Jude Bellingham (England)",
  "Julián Álvarez (Argentina)",
  "Kai Havertz (Germany)",
  "Kendry Páez (Ecuador)",
  "Kylian Mbappé (France)",
  "Lamine Yamal (Spain)",
  "Lautaro Martínez (Argentina)",
  "Lionel Messi (Argentina)",
  "Luis Díaz (Colombia)",
  "Marcus Rashford (England)",
  "Mathys Tel (France)",
  "Mohamed Salah (Egypt)",
  "Niclas Füllkrug (Germany)",
  "Ollie Watkins (England)",
  "Ousmane Dembélé (France)",
  "Paulo Dybala (Argentina)",
  "Phil Foden (England)",
  "Rafael Leão (Portugal)",
  "Randal Kolo Muani (France)",
  "Richarlison (Brazil)",
  "Rodrygo (Brazil)",
  "Romelu Lukaku (Belgium)",
  "Sadio Mané (Senegal)",
  "Santiago Giménez (Mexico)",
  "Son Heung-min (South Korea)",
  "Theo Hernández (France)",
  "Vinicius Jr (Brazil)",
  "Victor Osimhen (Nigeria)",
  "Xavi Simons (Netherlands)",
  "Álvaro Morata (Spain)",
  "Andrej Kramarić (Croatia)",
  "Ferran Torres (Spain)",
  "Other",
];

export const GOLDEN_GLOVE_PLAYERS: string[] = [
  "Agustín Marchesín (Argentina)",
  "Alisson Becker (Brazil)",
  "Alireza Beiranvand (Iran)",
  "Bono / Yassine Bounou (Morocco)",
  "David Raya (Spain)",
  "Diogo Costa (Portugal)",
  "Ederson (Brazil)",
  "Emiliano Martínez (Argentina)",
  "Gregor Kobel (Switzerland)",
  "Guillermo Ochoa (Mexico)",
  "Jan Oblak (Slovenia)",
  "Jordan Pickford (England)",
  "Kim Seung-gyu (South Korea)",
  "Kristoffer Klaesson (Norway)",
  "Łukasz Fabiański (Poland)",
  "Marcin Bułka (Poland)",
  "Mathew Ryan (Australia)",
  "Matt Turner (United States)",
  "Manuel Neuer (Germany)",
  "Marc-André ter Stegen (Germany)",
  "Mike Maignan (France)",
  "Patrick Pentz (Austria)",
  "Remko Pasveer (Netherlands)",
  "Robert Sánchez (Spain)",
  "Robin Olsen (Sweden)",
  "Rui Patrício (Portugal)",
  "Stefan Ortega (Germany)",
  "Thibaut Courtois (Belgium)",
  "Unai Simón (Spain)",
  "Wojciech Szczęsny (Poland)",
  "Yann Sommer (Switzerland)",
  "Other",
];

export const BEST_YOUNG_PLAYERS: string[] = [
  "Alejandro Garnacho (Argentina)",
  "Arda Güler (Turkey)",
  "Bradley Barcola (France)",
  "Cole Palmer (England)",
  "Désiré Doué (France)",
  "Eduardo Camavinga (France)",
  "Endrick (Brazil)",
  "Estêvão (Brazil)",
  "Facundo Buonanotte (Argentina)",
  "Florian Wirtz (Germany)",
  "Gavi (Spain)",
  "Jamal Musiala (Germany)",
  "Jobe Bellingham (England)",
  "Jude Bellingham (England)",
  "Kendry Páez (Ecuador)",
  "Kobbie Mainoo (England)",
  "Lamine Yamal (Spain)",
  "Leny Yoro (France)",
  "Mathys Tel (France)",
  "Michael Olise (France)",
  "Noni Madueke (England)",
  "Pau Cubarsí (Spain)",
  "Pedri (Spain)",
  "Rayan Cherki (France)",
  "Romeo Lavia (Belgium)",
  "Ryan Gravenberch (Netherlands)",
  "Santiago Giménez (Mexico)",
  "Tomas Aviles (United States)",
  "Vitor Roque (Brazil)",
  "Warren Zaïre-Emery (France)",
  "Xavi Simons (Netherlands)",
  "Youssoufa Moukoko (Germany)",
  "Other",
];

export function playerListForQuestion(key: string): string[] {
  switch (key) {
    case "golden_ball":       return GOLDEN_BALL_PLAYERS;
    case "golden_boot":       return GOLDEN_BOOT_PLAYERS;
    case "golden_glove":      return GOLDEN_GLOVE_PLAYERS;
    case "best_young_player": return BEST_YOUNG_PLAYERS;
    default: return [];
  }
}
